# Site settings
title: Galvin's ML blog
email: galvin.s.k@gmail.com
description: >-
  Informal place to document general ML learnings
baseurl: ""
url: "https://galvsk.github.io"

# Build settings
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "dark"
future: true
sass:
  sass_dir: _sass
  style: compressed

# Site Author
author:
  name: "Galvin Khara"
  avatar:
  bio: "ML Researcher"
  location: "London, UK"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/galvsk"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/galvin-khara-b6503390"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=6o0J7bQAAAAJ&hl=en"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/galvsk"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/galvin-khara-b6503390"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=6o0J7bQAAAAJ&hl=en"

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      toc: true
      toc_sticky: true
      toc_label: "Contents"
      toc_levels: 1..2
  - scope:
      path: ""
      type: home
    values:
      layout: home
      author_profile: true

# Reading Files
include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Pagination
paginate: 5
paginate_path: /page:num/

# Search
search: true
