name: Preview Drafts

on:
  push:
    branches:
      - drafts
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          
      - name: Build site with drafts
        run: JEKYLL_ENV=production bundle exec jekyll build --drafts
        env:
          JEKYLL_ENV: production
        
      - name: Deploy to drafts directory
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: drafts
          publish_branch: main
