name: Preview Drafts

on:
  push:
    branches:
      - drafts
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
          
      - name: Build site with drafts
        run: |
          bundle install
          bundle exec jekyll build --drafts
        
      - name: Deploy to drafts directory
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: drafts
          publish_branch: main
