name: Preview Drafts

on:
  push:
    branches:
      - drafts
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Move drafts to posts
        run: |
          mkdir -p _posts
          cp _drafts/* _posts/
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Build
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: main
